<?php

namespace Insig\AWSBundle\Tests;

use Insig\AWSBundle\ItemLookupRequest;

/**
 * Test class for ItemLookupRequest.
 * Generated by PHPUnit on 2011-02-17 at 12:03:50.
 */
class ItemLookupRequestTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ItemLookupRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ItemLookupRequest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testDefaults()
    {
        $this->assertSame('ItemLookup', $this->object->getParameter('Operation'));
    }

    /**
     * @expectedException InvalidArgumentException
     */
    public function testSetInvalidUPC()
    {
        $this->object->setUPC('012345678900');
    }

    /**
     * @expectedException Insig\AWSBundle\Exception
     */
    public function testSetUPCNullException()
    {
        $this->object->setUPC();
    }

    public function testSetUPC()
    {
        $this->object->setUPC('012345678905');
        $this->assertSame('012345678905', $this->object->getParameter('ItemId'));
        $this->assertSame('UPC', $this->object->getParameter('IdType'));
        $this->assertSame('DVD', $this->object->getParameter('SearchIndex'));
    }

    /**
     * @expectedException Insig\AWSBundle\Exception
     */
    public function testSetASINNullException()
    {
        $this->object->setASIN();
    }

    public function testSetASIN()
    {
        $this->object->setASIN(' B002Y27P3M ');
        $this->assertSame('B002Y27P3M', $this->object->getParameter('ItemId'));
        $this->assertSame('ASIN', $this->object->getParameter('IdType'));
    }
}
